# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucivari', '0004_document_original_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pdffilename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='reportfilename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
