# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucivari', '0006_templatefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='generic_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
