# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucivari', '0007_document_generic_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='content_file_generic',
            fields=[
                ('generic', models.TextField(blank=True, db_column='filename', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'generic',
                'managed': False,
            },
        ),
    ]
